name: Deploy beta

on:
    workflow_dispatch:

jobs:
    echo-branch:
        # Check if running on allowed branch
        if: ${{ contains('refs/heads/master, refs/heads/staging', github.ref) }}
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
              with:
                  ref: staging

            - name: Echo branch
              run: echo "Running on branch '${GITHUB_REF##*/}'"

            - name: Echo from script
              run: bash test.sh
