name: Deploy beta

on:
    workflow_dispatch:

jobs:
    validate-branch:
        # Check if running on allowed branch
        if: ${{ contains('refs/heads/master, refs/heads/staging', github.ref) }}
        runs-on: ubuntu-latest
        steps:
            - name: Confirm
              run: echo "Branch is allowed to be processed"

    echo-branch:
        runs-on: ubuntu-latest
        needs:
            - validate-branch
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
              with:
                  ref: staging

            - name: Echo branch
              run: echo "Running on branch '${GITHUB_REF##*/}'"

            - name: Echo from script
              run: bash test.sh

    echo-2:
        runs-on: ubuntu-latest
        needs:
            - echo-branch
        steps:
            - name: Echo
              run: echo "Goodbye"
