name: Deploy beta

on:
    workflow_dispatch:

jobs:
    echo-branch:
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Echo branch
              run: echo "Running on branch '${GITHUB_REF##*/}'"
